import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
      </head>
      
      <body className="min-h-screen bg-white">
        <a href="/" className="inline-block bg-blue-600 text-white px-2 py-1 xl:px-4 xl:py-2 rounded hover:bg-blue-700" > Home </a>
        <a href="/order" className="inline-block bg-blue-600 text-white px-2 py-1 xl:px-4 xl:py-2 rounded hover:bg-blue-700" > Order </a>
        <a href="/summary" className="inline-block bg-blue-600 text-white px-2 py-1 xl:px-4 xl:py-2 rounded hover:bg-blue-700" > Summary </a>
        {children}
      </body>
    </html>
  );
}

